### ISSUE TITLE
Profile dropdown limited to show only 16 results?

### ISSUE THREAD

**Issue by petednz** [agileware/au.com.agileware.civicontactapi#2]
maybe something else inteferring but i created a new Profile without First and Last and with a custom field used for Contacts. I went to find it in the dropdown at /civicrm/cca/settings but didn't see it.

I then compared the list i was seeing with a 'sorted by id' list at /civicrm/admin/uf/group and realised i was only seeing the first 16 of my profiles in the CCA dropdown

**Comment by agileware-justin** [comment]
@petednz how many custom fields are in that CiviCRM DB? Over 25?

**Comment by petednz** [comment]
Yes.

**Comment by agileware-justin** [comment]
Well, I reckon it's the classic, default limit of 25 results for CiviCRM APIv3 bug. Which means all the APIv3 get calls need to be updated to include LIMIT 0 - so all the results are included.

**Comment by agileware-justin** [comment]
I've bugged that to be fixed, Agileware Ref: CCA-357

**Comment by agileware-justin** [comment]
@petednz just letting you know that this is fixed in version 0.3.3
