### ISSUE TITLE
When I set the CiviContact profile, there is an error: 'county' is not a valid option for field field_name

### ISSUE THREAD

**Issue by johncronan** [agileware/au.com.agileware.civicontactapi#3]
- Server OS: Ubuntu 18.04.4
 - PHP Version: 7.2.24
- CiviCRM Version: 5.23.4
- Website CMS: Drupal 8.8.4

I cloned civicontactapi into my extensions directory as a new directory, civicontact.

When I enabled the extension, I didn't have any default settings at CiviContact -> Settings. At first, I set up everything but the profile and it saved okay. Then I tried to set a profile. (I don't think a new CiviContact profile was created for me, so just trying to set any profile.)

I get an error: 'county' is not a valid option for field field_name

I now cannot return to the CiviContact settings page: same error message. I tried disabling and reenabling the module. I tried all the troubleshooting steps in the template.

If I try to log in with QR code, on Android, I get an error saying, "Some error occured [sic] while fetching location types." I had this error on login even before I had tried to set the CiviContact profile.

**Comment by agileware-justin** [comment]
@johncronan thanks for the report, we will investigate.

> Some error occured [sic] while fetching location types

We have received a couple of reports of this specific error message, I'll bug that to be investigated too https://github.com/agileware/au.com.agileware.civicontact/issues/4

**Comment by gzh1960** [comment]
Guys just wanted to advise I had exactly the same issue as John above using Wordpress and Civicrm 5.25.

**Comment by guyiac** [comment]
Getting the same error with Drupal 7 and CiviCRM 5.34.0

**Comment by agileware-justin** [comment]
If you save the CiviContact Settings page and see the following error: _'county' is not a valid option for field field_name_. This error occurs when the **County** field in CiviCRM has been disabled, this field must be enabled for CiviContact to work correctly. CiviCRM County field is required for CiviContact.

Depending on the localisation of your CiviCRM, this field may be displayed in CiviCRM as either: County, Shire or some other name in your selected locale.
For simplicity, we will refer to this as the **County** field. 

Go to **Administer CiviCRM -> Localization -> Address Settings** and in the section **Address Editing, Address Fields**, enable the **County** option.

If the **County** field is not enabled then any API requests for the County field will be rejected by the CiviCRM and instead return an error response.

**Comment by guyiac** [comment]
Thanks Justin!

Guy Iaccarino
Greenleaf Advancement
Phone: 203-624-4636, ext. 111
Post: PO Box 617, Guilford CT 06437
Email <mailto:guyiac@greenleafadvancement.com> | Website <http://greenleafadvancement.com/> | LinkedIn <http://www.linkedin.com/in/guyiac> | Twitter <http://twitter.com/greenleaf_adv>




On Feb 18, 2021, at 7:46 PM, Justin Freeman <notifications@github.com> wrote:


If you save the CiviContact Settings page and see the following error: 'county' is not a valid option for field field_name. This error occurs when the County field in CiviCRM has been disabled, this field must be enabled for CiviContact to work correctly. CiviCRM County field is required for CiviContact.

Depending on the localisation of your CiviCRM, this field may be displayed in CiviCRM as either: County, Shire or some other name in your selected locale.
For simplicity, we will refer to this as the County field.

Go to Administer CiviCRM -> Localization -> Address Settings and in the section Address Editing, Address Fields, enable the County option.

If the County field is not enabled then any API requests for the County field will be rejected by the CiviCRM and instead return an error response.
