### ISSUE TITLE
When I try to log in, I get a message "Login Unsuccessful, Some error while fetching favourites."

### ISSUE THREAD

**Issue by guyiac** [agileware/au.com.agileware.civicontactapi#5]
Drupal 7, Civi 5.34.0, PHP 7.3

Able to install CiviContact API successfully on the server, but when I try to authenticate via the email or QR Code method on my iPhone SE with IOS 14.4, I get this message: "Login Unsuccessful, Some error while fetching favourites."

Any ideas?

**Comment by MegaphoneJon** [comment]
I just submitted PR #7 which fixes this.

**Comment by agileware-fj** [comment]
Per @MegaphoneJon's comment, PR#7 should address this issue.
